# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - skip-changelog
  ignore:
    # Checkstyle >=10 requires Java 11+
    - dependency-name: "com.puppycrawl.tools:checkstyle"
      versions: [">= 10.0"]
