name: 'Github base Continuous Integration'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:

    runs-on: [ ubuntu-latest ]
    name: Coverage on Ubuntu

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      # https://github.com/jenkins-infra/github-reusable-workflows/issues/36
      - name: Set up Maven
        run: |
          wget --no-verbose https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          echo $CHECKSUM apache-maven-$MAVEN_VERSION-bin.tar.gz | sha512sum --check
          tar xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
          rm apache-maven-$MAVEN_VERSION-bin.tar.gz
          sudo mv apache-maven-$MAVEN_VERSION /opt/maven
          sudo rm -f /usr/bin/mvn
          sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn
          mvn --version
        env:
          MAVEN_VERSION: 3.9.13
          # https://downloads.apache.org/maven/maven-3/3.9.13/binaries/apache-maven-3.9.13-bin.tar.gz.sha512
          CHECKSUM: 9c9933db7552869c1c4d45d9eaff34291599273929c010086e07dc78b090d7b393467a94fd1d9cc96201856b71723f2501a6ac94907248021f83eb277651cf26
      - name: Generate coverage with JaCoCo
        run: mvn --batch-mode clean verify jacoco:prepare-agent test jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./target/site/jacoco/jacoco.xml
          verbose: true
